apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: frontend
      port: 8100
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer    
