apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  ports:
    - name: proxy
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: reverseproxy
  type: LoadBalancer    

